In [1]:
import torch
from torch import nn

out = nn.Linear(3, 20)

x = torch.randn(10, 3)

out(x).shape

torch.Size([10, 20])

In [2]:
x = torch.randn(10, 6)

out(x).shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x6 and 3x20)

In [3]:
x = torch.randn(10, 3 * 20)

out(x).shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x60 and 3x20)

In [17]:
from torch import nn
import torch

d_model = 6
max_len = 5

position = torch.arange(0, max_len,
                        dtype=torch.float32).unsqueeze(1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [18]:
import math

div_term = torch.exp(
    torch.arange(0, d_model, 2, dtype=torch.float32) *
    -(math.log(10000.0) / d_model))
div_term

tensor([1.0000, 0.0464, 0.0022])

In [19]:
pe = torch.zeros(max_len, d_model)
pe

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [21]:
pe[:, 0::2] = torch.sin(position * div_term)
pe[:, 1::2] = torch.cos(position * div_term)
pe

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
        [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000]])